import { supabase } from './supabaseClient.js';
import { computeQuotationTotals, computeItemAmount } from '../utils/quotationCalculations.js';

const TABLE = 'quotations';
const ITEMS_TABLE = 'quotation_items';

/*
  Quotations service layer.

  quotation_number is NEVER set here — it's generated by a Postgres
  trigger (see database/migrations/20260815100000_quotation_numbering.sql)
  the moment a row is inserted without one. This service simply never
  sends that column on insert.

  Line items are saved with a straightforward "replace all" strategy
  on update (delete existing rows for this quotation, insert the
  current set) rather than a diff/patch — simpler and safe here since
  quotation_items have no independent identity outside their parent
  quotation (nothing else references a specific item row).
*/

function toItemRow(quotationId, item, index) {
  return {
    quotation_id: quotationId,
    product_id: item.product_id || null,
    description: item.description,
    quantity: Number(item.quantity),
    unit: item.unit || 'pcs',
    rate: Number(item.rate),
    gst_percentage: item.gst_percentage === '' || item.gst_percentage === null ? 18 : Number(item.gst_percentage),
    amount: computeItemAmount(item.quantity, item.rate),
    sort_order: index,
  };
}

export async function listQuotations({
  search = '',
  status = '',
  sortBy = 'quotation_date',
  ascending = false,
  page = 1,
  pageSize = 10,
} = {}) {
  let query = supabase.from(TABLE).select('*, client:clients(id, company_name)', { count: 'exact' });

  const term = search.trim();
  if (term) {
    const pattern = `%${term}%`;
    const orParts = [`quotation_number.ilike.${pattern}`];
    const { data: matchingClients } = await supabase.from('clients').select('id').ilike('company_name', pattern);
    const clientIds = (matchingClients ?? []).map((c) => c.id);
    if (clientIds.length > 0) {
      orParts.push(`client_id.in.(${clientIds.join(',')})`);
    }
    query = query.or(orParts.join(','));
  }

  if (status) {
    query = query.eq('status', status);
  }

  query = query.order(sortBy, { ascending });

  const from = (page - 1) * pageSize;
  const to = from + pageSize - 1;
  query = query.range(from, to);

  const { data, error, count } = await query;
  if (error) throw error;
  return { data: data ?? [], count: count ?? 0 };
}

export async function getQuotationWithItems(id) {
  const { data: quotation, error } = await supabase
    .from(TABLE)
    .select('*, client:clients(id, company_name, email, phone, address, city, state, gst_number)')
    .eq('id', id)
    .single();
  if (error) throw error;

  const { data: items, error: itemsError } = await supabase
    .from(ITEMS_TABLE)
    .select('*')
    .eq('quotation_id', id)
    .order('sort_order', { ascending: true });
  if (itemsError) throw itemsError;

  return { ...quotation, items: items ?? [] };
}

/**
 * @param {{client_id:string, quotation_date:string, valid_until:string|null, discount:number, notes:string|null}} quotation
 * @param {Array} items
 */
export async function createQuotation(quotation, items) {
  const totals = computeQuotationTotals(items, quotation.discount);

  const { data: created, error } = await supabase
    .from(TABLE)
    .insert({
      client_id: quotation.client_id,
      quotation_date: quotation.quotation_date,
      valid_until: quotation.valid_until || null,
      subtotal: totals.subtotal,
      discount: totals.discount,
      gst: totals.gst,
      total: totals.total,
      status: 'DRAFT',
      notes: quotation.notes || null,
      // quotation_number intentionally omitted — the DB trigger sets it.
    })
    .select()
    .single();
  if (error) throw error;

  if (items.length > 0) {
    const rows = items.map((item, index) => toItemRow(created.id, item, index));
    const { error: itemsError } = await supabase.from(ITEMS_TABLE).insert(rows);
    if (itemsError) throw itemsError;
  }

  return created;
}

export async function updateQuotation(id, quotation, items) {
  const totals = computeQuotationTotals(items, quotation.discount);

  const { data: updated, error } = await supabase
    .from(TABLE)
    .update({
      client_id: quotation.client_id,
      quotation_date: quotation.quotation_date,
      valid_until: quotation.valid_until || null,
      subtotal: totals.subtotal,
      discount: totals.discount,
      gst: totals.gst,
      total: totals.total,
      notes: quotation.notes || null,
    })
    .eq('id', id)
    .select()
    .single();
  if (error) throw error;

  const { error: deleteError } = await supabase.from(ITEMS_TABLE).delete().eq('quotation_id', id);
  if (deleteError) throw deleteError;

  if (items.length > 0) {
    const rows = items.map((item, index) => toItemRow(id, item, index));
    const { error: itemsError } = await supabase.from(ITEMS_TABLE).insert(rows);
    if (itemsError) throw itemsError;
  }

  return updated;
}

export async function updateQuotationStatus(id, status) {
  const { data, error } = await supabase.from(TABLE).update({ status }).eq('id', id).select().single();
  if (error) throw error;
  return data;
}

/** Only ever called for DRAFT quotations — enforced in the UI. */
export async function deleteQuotation(id) {
  const { error } = await supabase.from(TABLE).delete().eq('id', id);
  if (error) throw error;
}

export async function duplicateQuotation(id) {
  const original = await getQuotationWithItems(id);

  const newQuotation = {
    client_id: original.client_id,
    quotation_date: new Date().toISOString().slice(0, 10),
    valid_until: null,
    discount: original.discount,
    notes: original.notes,
  };
  const items = original.items.map((item) => ({
    product_id: item.product_id,
    description: item.description,
    quantity: item.quantity,
    unit: item.unit,
    rate: item.rate,
    gst_percentage: item.gst_percentage,
  }));

  return createQuotation(newQuotation, items);
}

/**
 * Efficient count-only query (head request, no rows fetched) for the
 * Dashboard's Business Overview cards.
 * @param {string[]} statuses
 */
export async function countQuotationsByStatus(statuses) {
  const { count, error } = await supabase.from(TABLE).select('id', { count: 'exact', head: true }).in('status', statuses);
  if (error) throw error;
  return count ?? 0;
}
