-- ============================================================
-- Henil Enterprise — Database Schema
-- 29. Artwork Vault: artworks, versions, storage, RBAC module
-- ============================================================
-- A manufacturing design archive, separate from the general
-- project-files bucket (customer-submitted drawings attached to a
-- client/quotation/invoice). Artwork Vault entries are the business's
-- OWN design records — reusable across many jobs, explicitly
-- versioned, and searchable by material/thickness/tags in their own
-- right, not just attached to one document.

create table if not exists public.artworks (
  id uuid primary key default gen_random_uuid(),
  artwork_code text not null unique,
  artwork_name text not null,
  client_id uuid references public.clients (id) on delete set null,
  product_id uuid references public.products (id) on delete set null,
  material text,
  thickness text,
  width numeric(10, 2),
  height numeric(10, 2),
  quantity integer,
  notes text,
  tags text[] not null default '{}',
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint chk_artworks_status check (status in ('ACTIVE', 'ARCHIVED')),
  constraint chk_artworks_width check (width is null or width > 0),
  constraint chk_artworks_height check (height is null or height > 0),
  constraint chk_artworks_quantity check (quantity is null or quantity >= 0)
);

create index if not exists idx_artworks_client_id on public.artworks (client_id);
create index if not exists idx_artworks_product_id on public.artworks (product_id);
create index if not exists idx_artworks_tags on public.artworks using gin (tags);
create index if not exists idx_artworks_material on public.artworks (material);

comment on table public.artworks is 'Manufacturing artwork/design archive — reusable design records, distinct from one-off customer files attached to a document (see public.files).';
comment on column public.artworks.artwork_code is 'Human-readable identifier (e.g. ART-00001), auto-generated by set_artwork_code() below — never entered by the app.';

-- Every uploaded file is a VERSION, never a silent overwrite. Old
-- versions are never deleted by the application; "current version"
-- is just a flag on one row, not a replacement of the others.
create table if not exists public.artwork_versions (
  id uuid primary key default gen_random_uuid(),
  artwork_id uuid not null references public.artworks (id) on delete cascade,
  version_number integer not null,
  file_path text not null,
  file_name text not null,
  file_type text,
  file_size bigint,
  is_current boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),

  constraint uq_artwork_versions_number unique (artwork_id, version_number),
  constraint chk_artwork_versions_file_size check (file_size is null or file_size >= 0)
);

create index if not exists idx_artwork_versions_artwork_id on public.artwork_versions (artwork_id);

-- Enforces "at most one current version per artwork" at the database
-- level, not just in application logic — a partial unique index
-- rather than a boolean-and-hope-the-app-remembers-to-flip-it-off.
create unique index if not exists uq_artwork_versions_one_current
  on public.artwork_versions (artwork_id) where (is_current);

comment on table public.artwork_versions is 'Every uploaded revision of an artwork, kept forever. is_current marks which one is authoritative right now; enforced unique per artwork via uq_artwork_versions_one_current.';

-- ---------- updated_at trigger (matches every other table) ----------
create trigger set_updated_at_artworks
  before update on public.artworks
  for each row execute function public.set_updated_at();

-- ---------- Auto-numbering (matches quotations/invoices exactly) ----------
create sequence if not exists public.artwork_code_seq;

create or replace function public.set_artwork_code()
returns trigger
language plpgsql
as $$
begin
  if new.artwork_code is null or new.artwork_code = '' then
    new.artwork_code := 'ART-' || lpad(nextval('public.artwork_code_seq')::text, 5, '0');
  end if;
  return new;
end;
$$;

create trigger trg_set_artwork_code
  before insert on public.artworks
  for each row execute function public.set_artwork_code();

-- ---------- RLS ----------
alter table public.artworks enable row level security;
alter table public.artwork_versions enable row level security;

drop policy if exists artworks_select on public.artworks;
drop policy if exists artworks_insert on public.artworks;
drop policy if exists artworks_update on public.artworks;
drop policy if exists artworks_delete on public.artworks;

create policy artworks_select on public.artworks for select using (public.has_module_access('artwork'));
create policy artworks_insert on public.artworks for insert with check (public.has_module_access('artwork'));
create policy artworks_update on public.artworks for update using (public.has_module_access('artwork')) with check (public.has_module_access('artwork'));
create policy artworks_delete on public.artworks for delete using (public.can_delete_module('artwork'));

drop policy if exists artwork_versions_select on public.artwork_versions;
drop policy if exists artwork_versions_insert on public.artwork_versions;
drop policy if exists artwork_versions_update on public.artwork_versions;
drop policy if exists artwork_versions_delete on public.artwork_versions;

create policy artwork_versions_select on public.artwork_versions for select using (public.has_module_access('artwork'));
create policy artwork_versions_insert on public.artwork_versions for insert with check (public.has_module_access('artwork'));
create policy artwork_versions_update on public.artwork_versions for update using (public.has_module_access('artwork')) with check (public.has_module_access('artwork'));
create policy artwork_versions_delete on public.artwork_versions for delete using (public.can_delete_module('artwork'));

-- ---------- Extend the RBAC module matrix: admin + manager ----------
-- Artwork is a production/design-adjacent capability, matching the
-- rest of Manager's existing scope (clients, products, quotations,
-- invoices, inventory, reports). Not added to sales/accounts/staff by
-- default; grant via a user's assigned_modules if a specific person
-- needs it (e.g. a workshop lead on the STAFF role).
create or replace function public.role_has_module(p_role text, p_module text)
returns boolean
language sql
immutable
as $$
  select case
    when p_role = 'admin' then true
    when p_role = 'manager' then p_module in ('clients', 'products', 'quotations', 'invoices', 'inventory', 'reports', 'artwork')
    when p_role = 'sales' then p_module in ('clients', 'products', 'quotations')
    when p_role = 'accounts' then p_module in ('invoices', 'payments', 'finance', 'expenses', 'reports')
    when p_role = 'staff' then p_module in ('inventory')
    else false
  end;
$$;

-- ---------- Storage bucket ----------
-- PRIVATE (these are the business's own design IP, if anything more
-- sensitive than a customer's one-off drawing) and a larger size
-- limit than project-files (20MB) since complex multi-layer AI/EPS
-- or dense DXF/CAD files commonly run larger than a simple PDF/photo.
insert into storage.buckets (id, name, public, file_size_limit)
values ('artwork-files', 'artwork-files', false, 52428800) -- 50 MB
on conflict (id) do nothing;

drop policy if exists artwork_files_select on storage.objects;
create policy artwork_files_select on storage.objects
  for select using (bucket_id = 'artwork-files' and public.has_module_access('artwork'));

drop policy if exists artwork_files_insert on storage.objects;
create policy artwork_files_insert on storage.objects
  for insert with check (bucket_id = 'artwork-files' and public.has_module_access('artwork'));

drop policy if exists artwork_files_delete on storage.objects;
create policy artwork_files_delete on storage.objects
  for delete using (bucket_id = 'artwork-files' and public.can_delete_module('artwork'));

comment on column public.artwork_versions.file_type is 'Lowercase extension (svg, dxf, pdf, ai, eps, png, jpg, jpeg, dwg) — validated by the application allow-list before upload, same pattern as public.files.';
